package net.chris.news.fondue.domain

data class News(
    val alias: String?,
    val boardid: String?,
    val cid: String?,
    val commentStatus: Int = 0,
    val daynum: String?,
    val digest: String?,
    val docid: String?,
    val ename: String?,
    val hasAD: Int = 0,
    val hasCover: Boolean = false,
    val hasHead: Int = 0,
    val hasIcon: Boolean = false,
    val hasImg: Int = 0,
    val imgsrc: String?,
    val lmodify: String?,
    val ltitle: String?,
    val mtime: String?,
    val order: Int = 0,
    val postid: String?,
    val priority: Int = 0,
    val ptime: String?,
    val quality: Int = 0,
    val replyCount: Int = 0,
    val source: String?,
    val sourceId: String?,
    val subtitle: String?,
    val template: String?,
    val title: String?,
    val tname: String?,
    val topic_background: String?,
    val url: String?,
    val url_3w: String?,
    val votecount: Int = 0
)
